version: 2
jobs:
  build:
    docker:
      #- image: haskell
      - image: phadej/ghc:8.4.2
    steps:
      - checkout
      - run: apt update 
      - run: apt install unzip
      - restore-cache:
          keys:
            - cabal-{{ checksum "website.cabal" }}
      - run: cabal update
      - run: cabal new-build
      - save-cache:
          key: cabal-{{ checksum "website.cabal" }}
          paths:
            - "~/.cabal/store"
            - "dist-newstyle/build"

workflows:
  version: 2
  run:
    jobs:
      - build
