version: 2
jobs:
  build:
    docker:
      #- image: haskell
      - image: phadej/ghc:8.4.2
    steps:
      - checkout
      - run: ghc --version
      - run: cabal --version
      - run: stack --version

workflows:
  version: 2
  run:
    jobs:
      - build
