version: 2
jobs:
  build:
    docker:
      #- image: haskell
      - image: phadej/ghc:8.4.2
    steps:
      - checkout
      - run: apt update 
      - run: apt install unzip
      - run: cabal update
      - run: cabal new-build

workflows:
  version: 2
  run:
    jobs:
      - build
